export const ON_UPDATE_WATCHED_MOVIES_REQUEST = 'mediaApp/ON_UPDATE_WATCHED_MOVIES_REQUEST';
export const ON_UPDATE_WATCHED_MOVIES_SUCCESS = 'mediaApp/ON_UPDATE_WATCHED_MOVIES_SUCCESS';
export const ON_UPDATE_WATCHED_MOVIES_ERROR = 'mediaApp/ON_UPDATE_WATCHED_MOVIES_ERROR';
